apiVersion: v1
data:
  API_KEY: MmY1YWU5NmMtYjU1OC00YzdiLWE1OTAtYTUwMWFlMWMzZjZj
  SECRET_KEY: dGVzdFBhc3N3b3Jk
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=

kind: Secret
metadata:
  creationTimestamp: null
  name: api-secrets
